django_curd/urls.py
from django.conf.urls import url
from django.contrib import admin
from curd import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # curd
    url(r'^add', views.Add.as_view(),name='add'),
    url(r'^list$', views.Listing.as_view(), name="list"),
    url(r'^edit/(?P<pk>\w+)$', views.Edit.as_view(),name='edit'),
    url(r'^delete/(?P<pk>\w+)$', views.Destroy.as_view(),name='delete'),

    # file operation
    url(r'^upload_files$', views.UploadFile.as_view(),name='upload_files'),
    url(r'^listing_files$', views.FileListing.as_view(),name='listing_files'),
    url(r'^download_zip$', views.DownloadZip.as_view(),name='download_zip'),
    url(r'^create_zip$', views.create_zip, name='zip'),

    # sftp,ssh telnet



]

curd/models.py
from django.db import models

class Telnet(models.Model):
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)
    class Meta:
        db_table = "telnet"

curd/forms.py
from django import forms
from curd.models import Telnet
from django.conf import settings


class TelnetForm(forms.ModelForm):
    id = forms.IntegerField(required=True)

    def clean_ename(self):
        return self.cleaned_data["ename"].strip()

    def save(self):
        Telnet.objects.filter(id=self.cleaned_data['id']).update(
            ename=self.cleaned_data['ename'],
            eemail=self.cleaned_data['eemail'],
            econtact=self.cleaned_data['econtact']
        )

    class Meta:
        model = Telnet
        fields = "__all__"

class UploadForm(forms.Form):
    title = forms.CharField(max_length=50)
    myfile = forms.FileField()

    def upload_file(self,file_data):
        with open(settings.MEDIA_ROOT + "/"+ file_data.name, 'wb+') as destination:
            for chunk in file_data.chunks():
                destination.write(chunk)

curd/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, DeleteView, FormView,View
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
from django.http import HttpResponse
from curd.forms import TelnetForm, UploadForm
from curd.models import Telnet
from zipfile import ZipFile
import os
from django.core.files import File
from django.conf import settings
import logging
logger = logging.getLogger(__name__)


class Add(CreateView):
    template_name = "index.html"
    form_class = TelnetForm
    http_method_names = ['get', 'post']
    success_url = reverse_lazy("list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        add_url = reverse_lazy("add")
        context_data["add_url"] = add_url
        return context_data

    def form_valid(self, form):
        self.object = form.save()
        return redirect(reverse_lazy('list'))

    def form_invalid(self, form):
        error = form.errors.get("__all__")
        if not error:
            error = form.errors
        return JsonResponse({'error': error}, status=400)

class Listing(ListView):
    model = Telnet
    template_name = 'show.html'
    http_method_names = ['get']

    # def get_queryset(self):
        # return self.queryset.filter(creator_id=self.request.user.id).order_by('-time_created'). \
        #     order_by('-last_updated')


    def get_context_data(self, **kwargs):
        context_data = {
            'employees':  Telnet.objects.all()
        }
        return context_data


class Edit(FormView):
    form_class = TelnetForm
    success_url = reverse_lazy("list_intents")
    template_name = 'edit.html'
    http_method_names = ['get', 'post']

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['employee'] = Telnet.objects.get(id=self.kwargs.get('pk'))
        edit_url = reverse_lazy("edit", kwargs={"pk": self.kwargs['pk']})
        context_data["edit_url"] = edit_url
        return context_data

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.
        """
        initial = super().get_initial()
        id = self.kwargs["pk"]
        return initial

    def form_valid(self, form):
        self.object = form.save()
        return redirect(reverse_lazy('list'))

    def form_invalid(self, form):
        error = form.errors.get("__all__")
        if not error:
            error = form.errors
        return JsonResponse({'error': error}, status=400)


class Destroy(DeleteView):
    queryset = Telnet.objects.all()
    http_method_names = ['delete']
    success_url = reverse_lazy('list')

    def delete(self, request, *args, **kwargs):
        pk = kwargs["pk"]
        telnet_obj = Telnet.objects.get(id=pk)
        telnet_obj.delete()
        return JsonResponse({'success': "Delete successfully"}, status=200)





class UploadFile(FormView):
    template_name = "upload.html"
    form_class = UploadForm
    http_method_names = ['get', 'post']
    success_url = reverse_lazy("listing_files")


    def form_valid(self, form):
        form.upload_file(form.files['myfile'])
        return redirect(reverse_lazy('upload_files'))

    def form_invalid(self, form):
        error = form.errors.get("__all__")
        if not error:
            error = form.errors
        return JsonResponse({'error': error}, status=400)



class FileListing(View):

    def get(self,request):
        context_data = {
            'file_listing':  os.listdir(settings.MEDIA_ROOT)
        }
        return render(request, 'file_listing.html', context_data)


class DownloadZip(View):

    def get(self, request):
        download_report_link = '/home/manish/backup/manish/workspace/again/media/manage.py'
        f = open(download_report_link, 'rb')
        file_obj = File(f)
        response = HttpResponse(file_obj, content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename=' + "UserResponsesReport.py"
        response['Content-length'] = file_obj.size
        os.remove(download_report_link)
        return response



def create_zip(request):
    filepath = '/home/manish/backup/manish/workspace/again/test.zip'
    with ZipFile(filepath, 'w') as zipf:
        # Add a file located at the source_path to the destination within the zip
        # file. It will overwrite existing files if the names collide, but it
        # will give a warning
        source_path = '/home/manish/backup/manish/workspace/again/manage.py'
        destination = 'manage.py'
        zipf.write(source_path, destination)

        zipf.printdir()

        # extracting all the files
        print('Extracting all the files now...')
        zipf.extractall()

    return JsonResponse({}, status=200)

curd/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<body>
<form method="POST" class="post-form" action="{{edit_url}}">
    {% csrf_token %}
    <input type="hidden" name="id"  value="{{ employee.id }}"/>
    <div class="container">
        <div>
            Employee Name: <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}"/>
        </div>
        <div>
           Employee Email: <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}"/>
        </div>
        <div>
            Employee Contact:  <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}"/>
        </div>
        <div>
            <button type="submit" class="btn btn-success">Update</button>
        </div>
    </div>
</form>
</body>
</html>

curd/templates/file_listing.html
<!DOCTYPE html>
<html lang="en">
<body>
<table>
    <thead>
    <tr>
        <th>File Name</th>
    </tr>
    </thead>
    <tbody>
    {% for file in file_listing %}
    <tr>
        <td>{{ file }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

curd/templates/index.html
<!DOCTYPE html>
<html lang="en">
<body>
<form method="POST" class="post-form" action="{{add_url}}">
    {% csrf_token %}
    <div class="container">
        <div class="form-group row">
                 Name:- {{ form.ename }}
        </div>
        <div class="form-group row">
                email:- {{ form.eemail }}
        </div>
        <div class="form-group row">
                contact:- {{ form.econtact }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
</body>
</html>

curd/templates/show.html
<!DOCTYPE html>
<html lang="en">
<body>
<table>
    <thead>
    <tr>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>Employee Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for employee in employees %}
    <tr>
        <td>{{ employee.ename }}</td>
        <td>{{ employee.eemail }}</td>
        <td>{{ employee.econtact }}</td>
        <td>
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
            <a href="javascript:void(0)" class="delete" data-href="/delete/{{ employee.id }}" >Delete</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<br>
<br>
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script>
var csrf = '{{ csrf_token }}'
$(function(){
    $(".delete").click(function(){
        ele_url = $(this).attr('data-href')
        $.ajax({
            url: ele_url,
            type: 'DELETE',
            headers: { "X-CSRFToken": csrf },
            success: function(result) {
               window.location.reload()
            }
        });
    });
})

</script>

<center><a href="{% url 'add' %}" class="btn btn-primary">Add New Record</a></center>
</body>
</html>

curd/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title">
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
</body>
</html>